title: Scout Blog
email: yaeesh.main@gmail.com
description: Scouting adventures and updates
baseurl: ""
url: https://scoutblog.yaeesh.dev
author: Yaeesh

# jekyllBear theme via remote_theme
remote_theme: knhash/jekyllBear

plugins:
  - jekyll-feed
  - jekyll-remote-theme
