title: Scout Blog
email: scout@yaeesh.dev
description: Yaeesh's Scouting Journey
baseurl: ""
url: https://scoutblog.yaeesh.dev
author: Yaeesh

remote_theme: knhash/jekyllBear

Blog: /blog

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-redirect-from
