title: Scout Blog
email: yaeesh.main@gmail.com
description: Scouting adventures and updates
baseurl: ""
url: https://scoutblog.yaeesh.dev
author: Yaeesh

remote_theme: knhash/jekyllBear

Blog: /blog

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-redirect-from
