backend:
  name: github
  repo: mYaeesh/scoutblog
  branch: main
  base_url: https://scoutblog-oauth.vercel.app
  auth_endpoint: /api/auth

site_url: https://scoutblog.yaeesh.dev
display_url: https://scoutblog.yaeesh.dev
logo_url: https://scoutblog.yaeesh.dev/assets/favicon.ico

media_folder: assets/images
public_folder: /assets/images

collections:
  - name: posts
    label: Blog Posts
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: md
    format: frontmatter
    fields:
      - { label: Layout, name: layout, widget: hidden, default: post }
      - { label: Title, name: title, widget: string }
      - label: Publish Date
        name: date
        widget: datetime
        format: "YYYY-MM-DD HH:mm:ss ZZ"
        date_format: "YYYY-MM-DD"
        time_format: "HH:mm"
      - label: Categories
        name: categories
        widget: list
        allow_add: true
        default: []
      - label: Tags
        name: tags
        widget: list
        allow_add: true
        default: []
      - { label: Body, name: body, widget: markdown }
